#pragma once

#include "Privmsg.hpp"
#include "Pass.hpp"
#include "Nick.hpp"
#include "Whois.hpp"
#include "Who.hpp"
#include "Ping.hpp"
#include "Part.hpp"
#include "List.hpp"
#include "Join.hpp"
#include "Quit.hpp"
#include "Topic.hpp"
#include "Motd.hpp"
#include "Kick.hpp"
#include "Invite.hpp"
#include "Mode.hpp"
#include <iostream>
#include <string>